// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// TipsPool is the golang structure for table informal_tips_pool.
type TipsPool struct {
	Id        int         `orm:"id,primary" json:"id"`        //
	Type      string      `orm:"type"       json:"type"`      //
	Content   string      `orm:"content"    json:"content"`   //
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` // 创建时间
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` // 更新时间
	DeletedAt *gtime.Time `orm:"deleted_at" json:"deletedAt"` // 删除时间
}
