// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"informal/app/dao/internal"
)

// tipsPoolDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tipsPoolDao struct {
	*internal.TipsPoolDao
}

var (
	// TipsPool is globally public accessible object for table informal_tips_pool operations.
	TipsPool tipsPoolDao
)

func init() {
	TipsPool = tipsPoolDao{
		internal.NewTipsPoolDao(),
	}
}

// Fill with you ideas below.
