// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// TipsPoolDao is the manager for logic model data accessing and custom defined data operations functions management.
type TipsPoolDao struct {
	gmvc.M                 // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      tipsPoolColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB          // DB is the raw underlying database management object.
	Table  string          // Table is the underlying table name of the DAO.
}

// TipsPoolColumns defines and stores column names for table informal_tips_pool.
type tipsPoolColumns struct {
	Id        string //
	Type      string //
	Content   string //
	CreatedAt string // 创建时间
	UpdatedAt string // 更新时间
	DeletedAt string // 删除时间
}

// NewTipsPoolDao creates and returns a new DAO object for table data access.
func NewTipsPoolDao() *TipsPoolDao {
	columns := tipsPoolColumns{
		Id:        "id",
		Type:      "type",
		Content:   "content",
		CreatedAt: "created_at",
		UpdatedAt: "updated_at",
		DeletedAt: "deleted_at",
	}
	return &TipsPoolDao{
		C:     columns,
		M:     g.DB("default").Model("informal_tips_pool").Safe(),
		DB:    g.DB("default"),
		Table: "informal_tips_pool",
	}
}
